# Generated by Django 2.1.2 on 2020-04-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20200412_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
    ]
