# Generated by Django 2.1.2 on 2020-04-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_food_is_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='is_sale',
            field=models.BooleanField(default=True),
        ),
    ]
