# Generated by Django 2.0.4 on 2020-04-30 13:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0006_food_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100, verbose_name='顧客名')),
                ('sub_total', models.IntegerField(verbose_name='小計')),
                ('tax', models.IntegerField(verbose_name='消費税')),
                ('total_amount', models.IntegerField(verbose_name='合計金額')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': '注文',
                'verbose_name_plural': '注文',
            },
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='単価')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='数量')),
                ('amount', models.IntegerField(verbose_name='金額')),
                ('Food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.Food', verbose_name='商品')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.Invoice')),
            ],
        ),
    ]
